site_url: https://juan-pablo-balderas-portfolio.pages.dev

backend:
  name: github
  repo: juanpablobalderas/juan.pablo.balderas.portfolio
  branch: main

media_folder: img
public_folder: /img

collections:
  - name: proyectos
    label: Proyectos
    folder: _proyectos
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titulo
        name: title
        widget: string
      - label: Año
        name: year
        widget: string
     - label: Categoria
        name: category
        widget: select
        options:
          - label: Direccion
            value: direccion
          - label: Visualizer
            value: visualizer
          - label: Fotografia
            value: fotografia
      - label: Rol
        name: role
        widget: string
      - label: Descripcion
        name: description
        widget: text
      - label: Imagen principal
        name: hero
        widget: image
        required: false
      - label: Video URL
        name: video
        widget: string
        required: false

  - name: about
    label: About
    files:
      - label: Sobre mi
        name: about
        file: _data/about.yml
        fields:
          - label: Bio
            name: bio
            widget: text
          - label: Research Statement
            name: statement
            widget: text
